FROM node:16-alpine3.18

# Create app directory

WORKDIR /app

# Install app dependencies

COPY ./package.json .

# For npm@5 or later, copy package-lock.json as well

COPY ./package-lock.json .

COPY babel.config.js .

COPY .env .

COPY lib/ ./lib/

# Comment out the below line if you are using docker-compose to deploy
COPY database/ ./database/

RUN npm install

# Bundle app source

COPY backend/ ./backend/

RUN cd backend && npm install

EXPOSE 5000

CMD [ "npm", "run", "start:backend" ]
