version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    volumes:
      - ./database:/app/database
    ports:
      - "5000:5000"

  websockets:
    build:
      context: .
      dockerfile: Dockerfile-websockets
    volumes:
      - ./database:/app/database
    ports:
      - "5001:5001"

# networks:
#   my-network:
