FROM node:16-alpine3.18

# Create app directory

WORKDIR /app

# Install app dependencies

COPY ./package.json .

# For npm@5 or later, copy package-lock.json as well

COPY ./package-lock.json .

COPY babel.config.js .

COPY .env .

COPY lib/ ./lib/

# Comment out the below line if you are using docker-compose to deploy
COPY database/ ./database/

RUN npm install

# Bundle app source

COPY websockets/ ./websockets/

RUN cd websockets && npm install

EXPOSE 5001

CMD [ "npm", "run", "start:websocket" ]
